AMS/FORM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("forms.urls")),
]

AMS/forms/urls.py
from django.urls import path
from .views import *

urlpatterns = [
	path("", home, name="home"),
	path("add_player/", add_player, name="add_player"),
	path("details/", player_details, name="details"),
	path("player/<int:pk>/", player_detail, name="player_detail"),
	path("create_form/", create_form, name = "create_form"),
	path('add_questions/<int:form_id>', add_questions, name="add_questions"),
	path('list_forms/', list_forms, name="list_forms"),
	path('form_detail/<int:form_id>/', form_detail, name="form_detail"),
	path("delete_form/<int:form_id>/", delete_form, name="delete_form"),
	path('recyclebin/', recycle_data, name="recycle"),
	path("restore/<int:form_id>/", restore_data, name="restore"),
	path("delete/<int:form_id>/", delete_data, name = "delete"),
	

]

AMS/forms/models.py
from django.db import models

# Create your models here.
class Team(models.Model):
	title = models.CharField(max_length = 100)

	def __str__(self):
		return self.title

# the player form
class Player(models.Model):
    GENDER_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    ]

    AGE_CATEGORY_CHOICES = [
        ('boys_under-15', 'Boys under 15'),
        ('boys_under-19', 'Boys under 19'),
        ('men_under-23', 'Men Under 23'),
        ('men_senior', 'Men Senior'),
    ]

    POSITION_CHOICES = [
        ('batsmen', 'Batsmen'),
        ('bowler', 'Bowler'),
        ('wicketkeeper', 'Wicketkeeper'),
        ('all_rounder', 'All Rounder'),
    ]

    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    profile = models.ImageField(upload_to="profiles/")
    nationality = models.CharField(max_length=100)
    dateofbirth = models.DateField()
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    aadhar = models.CharField(max_length=12)
    aadhar_photo = models.ImageField(upload_to="aadhar_photos/")
    emailid = models.EmailField()
    mobile = models.CharField(max_length=15)
    address = models.TextField()
    state = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    pincode = models.CharField(max_length=6)
    weight = models.DecimalField(max_digits = 5, decimal_places = 2)
    height = models.DecimalField(max_digits=5, decimal_places=2)
    guardian_name = models.CharField(max_length=100)
    relation = models.CharField(max_length=100)
    guardiancontact = models.CharField(max_length=15)
    agecategory = models.CharField(max_length=20, choices=AGE_CATEGORY_CHOICES)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    position = models.CharField(max_length=20, choices=POSITION_CHOICES)
    role = models.CharField(max_length=100)
    handiness = models.CharField(max_length=100)
    disease = models.CharField(max_length=100)
    allergies = models.TextField(blank = True, null = True)
    additional_information = models.TextField(blank = True, null = True)


    def __str__(self):
    	return f"{self.firstname} {self.lastname}"



# create form stuff
class Form(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank = True)
    IsDelete = models.BooleanField(default=False)

class Question(models.Model):
    QUESTION_TYPES = [
        ('short_answer', "Short Answer"),
        ('paragraph', "Paragraph"),
        ('multiple_choice', "Multiple Choice"),
        ('checkbox', "Check Boxes"),
        ('dropdown', "Dropdowns"),
        ('file_upload', "File Upload"),
        ('date', "Date"),
        ('time', "Time"),
    ]

    form = models.ForeignKey(Form, related_name = "questions", on_delete=models.SET_NULL, null = True)
    question_text = models.CharField(max_length=255)
    question_type = models.CharField(max_length=100, choices=QUESTION_TYPES)

    def __str__(self):
        return self.question_text

class Multiple_choice(models.Model):
    question = models.ForeignKey(Question, related_name='options', on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)

    def __str__(self):
        return self.choice_text

class Response(models.Model):
    form = models.ForeignKey(Form, on_delete=models.CASCADE)
    created_at= models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"Response for {self.form.title}"





AMS/forms/admin.py
from django.contrib import admin

# Register your models here.

AMS/forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'forms'

AMS/forms/forms.py
from django import forms
from .models import *

class PlayerForm(forms.ModelForm):
	team = forms.ModelChoiceField(queryset=Team.objects.all(), label="Select Team")

	class Meta:
		model = Player
		fields = '__all__'

# create form stuff

class CreateForm(forms.ModelForm):
	class Meta:
		model = Form
		fields = ['title', 'description']

AMS/forms/tests.py
from django.test import TestCase

# Create your tests here.

AMS/forms/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from .models import *

# Create your views here.
def home(request):
	return render(request, 'home.html')

# PLAYER FORM STUFF

def add_player(request):
	team = Team.objects.all()

	if request.method == 'POST':
		form = PlayerForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()

			return redirect('details')
	else:
		form = PlayerForm()

	context = {
		"form": form,
		"team": team,
	}

	return render(request, "add_player.html", context)

def player_details(request):
	players = Player.objects.all()

	context = {
		"players": players
	}

	return render(request, "details.html", context)

def player_detail(request):
	player = Player.object.get(pk = pk)

	context = {
		"player": player
	}

	return render(request, "player_detail.html", context)


# FORM CREATION FUNCTIONS
def create_form(request):
	if request.method == 'POST':
		# CreateForm is FormForm in the project
		create_form  = CreateForm(request.POST)
		if create_form.is_valid():
			created_form_instance = create_form.save()
			return redirect("add_questions", form_id = created_form_instance.id)
	else:
		create_form = CreateForm()

	context = {
		"create_form": create_form,
	}

	return render(request, "create_form.html", context)

def add_questions(request, form_id):
	created_form_instance = get_object_or_404(Form, id = form_id)

	if request.method == 'POST':
		question_text =request.POST.get('question_text')
		question_type = request.POST.get("question_type")
		choices = request.POST.get('options')

		question = Question.objects.create(
			form = created_form_instance,
			question_text = question_text,
			question_type = question_type
			)

		if question_type in ['multiple_choice', 'checkbox', 'dropdown']:
			choice_list = choices.split(",")
			for choice_text in choice_list:
				Multiple_choice.objects.create(question = question, choice_text = choice_text.strip())

		return redirect("add_questions", form_id = created_form_instance.id)

	questions = created_form_instance.questions.all()

	context = {
	"created_form_instance": created_form_instance,
	"questions": questions,
	}
	return render(request, "add_questions.html", context)

def list_forms(request):
	forms = Form.objects.filter(IsDelete = False)
	context = {'forms': forms}
	return render(request, 'list_forms.html', context)

def form_detail(request, form_id):
	form_instance = get_object_or_404(Form, id = form_id)
	responses = Response.objects.filter(form=form_instance).order_by('-created_at')

	if request.method == 'POST' and 'edit_response_id' in request.POST:
		response_id = request.POST.get('edit_response_id')
		return redirect('edit_response', response_id = response_id)

	context = {
		"form_instance" : form_instance,
		"responses": responses,
	}

	return render(request, 'form_detail.html', context)

def form_detail(request, form_id):
    form_instance = get_object_or_404(Form, id=form_id)
    questions = form_instance.questions.all()
    return render(request, 'form_detail.html', {'form_instance': form_instance, 'questions': questions})

def delete_form(request, form_id):
	form = get_object_or_404(Form, id = form_id)
	form.IsDelete = True
	form.save()
	# form.delete()
	return redirect("list_forms")

def recycle_data(request):
	forms = Form.objects.filter(IsDelete=True)
	context = {
		"forms": forms,
	}

	return render(request, "recycle.html", context)

def restore_data(request, form_id):
	form_instance = get_object_or_404(Form, id = form_id)
	form_instance.IsDelete = False
	form_instance.save()
	return redirect('list_forms')

def delete_data(request,form_id):
	form = get_object_or_404(Form, id = form_id)
	form.delete()
	return redirect('recycle')



AMS/forms/templates/add_player.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Add Player Form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- {% load static %} -->
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/add_player.css'%}"> -->

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">Home</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'add_player' %}">Add Player</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'details' %}">Details</a>
                </li>
            </ul>
        </div>
    </nav>
    {% if form.errors %}
    <div class="alert alert-danger">
        <ul>
            {% for field in form %}
            {% for error in field.errors %}
            <li>{{ field.label }}: {{ error }}</li>
            {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}

    <div class="container">
        <h2>Add New Player</h2>
        <form method="POST" action="" enctype="multipart/form-data" class="info">
            {% csrf_token %}
            <h3> Personal Information</h3>
            <div class="line"></div>
            <div class="input">
                <div class="mb-3 left">
                    <label for="firstname" class="form-label">Firstname</label>
                    <input type="text" class="form-control" id="firstname" name="firstname" >
                    {% if form.firstname.errors %}
                    <div class="error">{{ form.firstname.errors }}</div>
                    {% endif %}
                </div>
                <div class="mb-3 middle">
                    <label for="lastname" class="form-label">Lastname</label>
                    <input type="text" class="form-control" id="lastname" name="lastname">
                    {% if form.lastname.errors %}
                    <div class="error">{{ form.lastname.errors }}</div>
                    {% endif %}
                </div>
                <div class="mb-3 right">
                    <label for="profile" class="form-label">Profile Picture</label>
                    <input type="file" class="form-control" id="profile" name="profile">
                </div>
            </div>
            <div class="input">
                <div class="mb-3 left">
                    <label for="nationality" class="form-label">Nationality</label>
                    <input type="text" class="form-control" id="nationality" name="nationality">
                </div>
                <div class="mb-3 middle">
                    <label for="dateofbirth" class="form-label">Date of Birth </label>
                    <input type="date" class="form-control" id="dateofbirth" name="dateofbirth">
                </div>
                <div class="mb-3 right ">
                    <label for="gender" class="form-label" style="text-align:center;">Gender</label>
                    <div class="radiofield">
                        <div class="radio-1"><input type="radio" name="gender" value="Male">
                            <label for="gender" class="form-label" style="text-align:left;">Male</label>
                        </div>
                        <div class="radio-2"> <input type="radio" name="gender" value="Female">
                            <label for="gender" class="form-label" style="text-align:left;">Female</label>
                        </div>
                        <div class="radio-3"><input type="radio" name="gender" value="Other">
                            <label for="gender" class="form-label" style="text-align:left;">Other</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="input">
                <div class="mb-3 middle">
                    <label for="aadhar" class="form-label">Aadhar Number</label>
                    <input type="text" class="form-control" id="aadhar" name="aadhar">
                    {% if form.aadhar.errors %}
                    <div class="error">{{ form.aadhar.errors }}</div>
                    {% endif %}
                </div>
                <div class="mb-3 right">
                    <label for="aadhar_photo" class="form-label">Aadhar Image</label>
                    <input type="file" class="form-control" id="aadhar_photo" name="aadhar_photo">
                </div>
                <div class="mb-3 left">
                    <label for="emailid" class="form-label">Email Id</label>
                    <input type="email" class="form-control" id="emailid" name="emailid">
                </div>
            </div>
            <div class=" input">
                <div class="mb-3 left">
                    <label for="address" class="form-label">Residentinal Address</label>
                    <textarea id="address" class="form-control" name="address" rows='3'></textarea>
                </div>
                <div class="mb-3 middle">
                    <label for="state" class="form-label">State</label>
                    <input type="text" id="state" class="form-control" name="state">
                </div>
                <div class="mb-3 right">
                    <label for="district" class="form-label">District</label>
                    <input type="text" id="district" class="form-control" name="district">
                </div>
            </div>
            <div class="input">
                <div class="mb-3 left">
                    <label for="pincode" class="form-label">Pincode</label>
                    <input type="number" id="pincode" class="form-control" name="pincode">
                    {% if form.pincode.errors %}
                    <div class="error">{{ form.pincode.errors }}</div>
                    {% endif %}
                </div>
                <div class="mb-3 right ">
                    <label for="mobile" class="form-label">Mobile No</label>
                    <input type="text" class="form-control" id="mobile" name="mobile">
                    {% if form.mobile.errors %}
                    <div class="error">{{ form.mobile.errors }}</div>
                    {% endif %}
                </div>
            </div>
            <h3> Physical Information </h3>
            <div class="line"></div>
            <div class="input">
                <div class="mb-3 left">
                    <label for="weight" class="form-label">Weight </label>
                    <input type="number" step="0.1" class="form-control" id="weight" name="weight">
                    {% if form.weight.errors %}
                    <div class="error">{{ form.weight.errors }}</div>
                    {% endif %}
                </div>
                <div class="mb-3 right">
                    <label for="height" class="form-label">Height </label><br>
                    <input type="number" step="0.01" class="form-control" id="height" name="height">
                    {% if form.height.errors %}
                    <div class="error">{{ form.height.errors }}</div>
                    {% endif %}
                </div>
            </div>
            <h3> Guardian Information</h3>
            <div class="line"></div>
            <div class="input">
                <div class="mb-3 left">
                    <label for="guardian_name" class="form-label">Guardian Name</label>
                    <input type="text" class="form-control" id="guardian_name" name="guardian_name">
                    {% if form.guardian_name.errors %}
                    <div class="error">{{ form.guardian_name.errors }}</div>
                    {% endif %}
                </div>
                <div class="mb-3 middle">
                    <label for="relation" class="form-label">Relationship With Guardian</label>
                    <input type="text" class="form-control" id="relation" name="relation">
                    {% if form.relation.errors %}
                    <div class="error">{{ form.relation.errors }}</div>
                    {% endif %}
                </div>
                <div class="mb-3 right">
                    <label for="guardiancontact" class="form-label">Guardian Contact</label>
                    <input type="text" class="form-control" id="guardiancontact" name="guardiancontact">
                    {% if form.guardiancontact.errors %}
                    <div class="error">{{ form.guardiancontact.errors }}</div>
                    {% endif %}
                </div>
            </div>
            <h3> Player Information</h3>
            <div class="line"></div>
            <div class="input">
                <div class="mb-3 left">
                    <label for="agecategory" class="form-label">Age Wise Category</label>
                    <select class="form-control" id="agecategory" name="agecategory">
                        <option value="boys_under-15">Boys under15</option>
                        <option value="boys_under-19">Boys under19</option>
                        <option value="men_under-23">Mens Under23</option>
                        <option value="men_senior">Men Senior</option>
                    </select>
                </div>
                <div class="mb-3 middle">
                    <label for="team" class="form-label">Team </label>
                    <select class="form-control" id="team" name="team">
                        {% for team in team %}
                        <option value="{{team.id}}">{{team.title}} </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3 right">
                    <label for="position" class="form-label">Position</label>
                    <select class="form-control" id="position" name="position">
                        <option value="batsmen">Batsmen</option>
                        <option value="bowler">Bowler</option>
                        <option value="wicketkeeper">Wicketkeeper</option>
                        <option value="all_rounder">All Rounder</option>
                    </select>
                </div>
            </div>
            <div class="input">
                <div class="mb-3 left">
                    <label for="role" class="form-label">Role</label>
                    <input type="text" class="form-control" id="role" name="role">
                    {% if form.role.errors %}
                    <div class="error">{{ form.role.errors }}</div>
                    {% endif %}
                </div>
                <div class="mb-3 right">
                    <label for="handiness" class="form-label">Handiness</label>
                    <input type="text" class="form-control" id="handiness" name="handiness">
                </div>
            </div>
            <h3> Medical History Information</h3>
            <div class="line"></div>
            <div class="input">
                <div class="mb-3 left">
                    <label for="disease" class="form-label">Disease</label>
                    <input type="text" class="form-control" id="disease" name="disease">

                </div>
                <div class="mb-3 middle">
                    <label for="allergies" class="form-label">Allergies</label>
                    <textarea class="form-control" name="allergies" rows="4"></textarea>
                </div>
            </div>
            <div class="input">
                <div class="mb-3 left">
                    <label for="addidtional_information" class="form-label">Additional Information</label>
                    <textarea class="form-control" name="additional_information" rows="4"></textarea>
                </div>
            </div>
            <div class="btn-container">
                <button class="btn" href="{% url 'details' %}" type="submit" class="btn btn-info">Submit</button>
                <a class="btn" href="{% url 'home' %}" class="btn btn-info">Back</a>
            </div>
        </form>
    </div>
</body>

</html>

AMS/forms/templates/add_questions.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Add Questions</title>
    <link rel="stylesheet" type="text/css" href="{% static 'add_questions.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <h1>Add Questions to Form "{{ created_form_instance.title }}"</h1>

        <form method="post">
            {% csrf_token %}
            <div class="input-container">
                <label for="question_text">Question Text:</label>
                <input type="text" id="question_text" name="question_text" required>
            </div>
            <div class="input-container">
                <label for="question_type">Question Type:</label>
                <select id="question_type" name="question_type" required>
                    <option value="short_answer">Short Answer</option>
                    <option value="paragraph">Paragraph</option>
                    <option value="multiple_choice">Multiple Choice</option>
                    <option value="checkbox">Check Boxes</option>
                    <option value="dropdown">Dropdowns</option>
                    <option value="file_upload">File Upload</option>
                    <option value="date">Date</option>
                    <option value="time">Time</option>
                </select>
            </div>
            <div id="choices_div" style="display: none;">
                <label for="options">Choices (Comma-separated):</label>
                <input type="text" id="options" name="options">
            </div>
            <button type="submit">Add Question</button>
        </form>
        <div class="inner-container">
            <h2>Existing Questions</h2>
            <div class="line"></div>
            <ul>
                {% for question in questions %}
                <li>
                    <strong>{{ question.question_text }}</strong>
                    (Type: {{ question.get_question_type_display }})
                    {% if question.question_type in 'multiple_choice checkbox dropdown' %}
                    <ul>
                        {% for choice in question.options.all %}
                        <li>{{ choice.choice_text }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </li>
                {% empty %}
                <li>No questions added yet.</li>
                {% endfor %}
            </ul>

            <a href="{% url 'list_forms' %}">All Form Details</a>
        </div>
    </div>
    <script>
        document.getElementById('question_type').addEventListener('change', function () {
            var type = this.value;
            var choicesDiv = document.getElementById('choices_div');
            if (type === 'multiple_choice' || type === 'checkbox' || type === 'dropdown') {
                choicesDiv.style.display = 'block';
            } else {
                choicesDiv.style.display = 'none';
            }
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-zJ3+PoYG2hIe7w6FIp40/xzWq58jz3IMtkJqjRn5YqUo2+0D98IjOBhp0+P8DrMo"
        crossorigin="anonymous"></script>
</body>

</html>

AMS/forms/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My App</title>
    
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> -->
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'add_player' %}">Add Player</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'details' %}">Details</a>
                    </li>
                    
                    {% for player in players %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'player_detail' player.id %}">{{ player.firstname }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-zJ3+PoYG2hIe7w6FIp40/xzWq58jz3IMtkJqjRn5YqUo2+0D98IjOBhp0+P8DrMo" crossorigin="anonymous"></script>
</body>
</html>

AMS/forms/templates/create_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Create Form</title>
    <link rel="stylesheet" type="text/css" href="{% static 'create_form.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <h1>Create Form</h1>
        <form method="post">
            {% csrf_token %}
            {{ create_form.as_p }}
            <button type="submit">Create Form</button>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-zJ3+PoYG2hIe7w6FIp40/xzWq58jz3IMtkJqjRn5YqUo2+0D98IjOBhp0+P8DrMo"
        crossorigin="anonymous"></script>
</body>

</html>

AMS/forms/templates/details.html
{% extends 'base.html' %}

{% block title %}
	Player Details
{% endblock %}

{% block content %}

<h2>Player Details</h2>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Firstname</th>
			<th>Lastname</th>
			<th>Nationality</th>
			<th>DOB</th>
			<th>Gender</th>
			<th>Email Id</th>
			<th>Mobile No</th>
			<th>Team</th>
			<th>Position</th>
			<th>More Info</th>
		</tr>
	</thead>

	<tbody>
		{% for player in players %}
			<tr>
				<td>{{ player.firstname }}</td>
				<td>{{ player.lastname}}</td>
				<td>{{ player.nationality }}</td>
				<td>{{ player.dateofbirth }}</td>
				<td>{{ player.gender }}</td>
				<td>{{ player.mobile }}</td>
				<td>{{ player.team.title }}</td>
				<td>{{ player.position }}</td>
				<td><a href="{% url 'player_detail' player.id %}"></a>View</td>
			</tr>
		{% endfor %}
	</tbody>
</table>

{% endblock %}

AMS/forms/templates/form_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Form Details</title>
    <link rel="stylesheet" type="text/css" href="{% static 'form_detail.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="inner-container">
            <h1>Form Details</h1>
            <h2>{{ form_instance.title }}</h2>
            <p>{{ form_instance.description }}</p>
            <h3>Questions</h3>
            <div class="line"></div>
            <ul>
                {% for question in questions %}
                <li>
                    {{ question.question_text }} ({{ question.get_question_type_display }})
                </li>
                {% empty %}
                <li>No questions available.</li>
                {% endfor %}
            </ul>
            <a href="">Add Response</a>
            <a href="">Send Form link</a>
            <a href="">Send Form link via whatsapp</a>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-zJ3+PoYG2hIe7w6FIp40/xzWq58jz3IMtkJqjRn5YqUo2+0D98IjOBhp0+P8DrMo"
        crossorigin="anonymous"></script>

</body>

</html>

AMS/forms/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1 class="display-4">Welcome to the Player Management System</h1>
    <p class="lead">This is a simple web application to manage player details.</p>
    <hr class="my-4">
    <p>Use the navigation bar to add new players or view player details.</p>
    <a class="btn btn-primary btn-lg" href="{% url 'add_player' %}" role="button">Add New Player</a>
    <a class="btn btn-secondary btn-lg" href="{% url 'details' %}" role="button">View Player Details</a>
    <a class="btn btn-secondary btn-lg" href="{% url 'create_form' %}" role="button">Create Form</a>
    <a href="{% url 'list_forms' %}" role="button">All Forms</a>
</div>
{% endblock %}